### ISSUE TITLE
Keyboard layout always reverted to US qwerty

### ISSUE THREAD

**Issue by lewtds** [Ubuntu-VN/ibus-unikey#2]
Steps:
- Remove all keyboard layouts in IBus
- Add US Dvorak and Unikey
- Switch to Dvorak, make sure that you can type in Dvorak
- Switch to Unikey

Expected: Can type Vietnamese with the Dvorak layout.
Result: The layout is reverted to US qwerty.

Also refer to: https://github.com/mrlequoctuan/ibus-unikey/issues/4

**Comment by lewtds** [comment]
FIXED: https://github.com/Ubuntu-VN/ibus-unikey/commit/15362d1ce95f7fa5c159e0d7b9d3ad8a30dd4944

**Comment by ztane** [comment]
I guess this didn't make it to Ubuntu 16.04?

**Comment by thuandt** [comment]
@ztane I'm switching to fcitx and fcitx-unikey since 15.10. I don't think ibus-unikey work well since 15.10

**Comment by ztane** [comment]
@thuandt Ah this works actually. I used [the instructions from wiki](https://github.com/Ubuntu-VN/wiki/wiki/G%C3%B5-ti%E1%BA%BFng-Vi%E1%BB%87t#b%C3%A0n-ph%C3%ADm-dvorak-hay-colemak) properly and set the `<layout>fi</layout>` and now Unikey works with Finnish layout. This is actually the very first time that I've succeeded in having TELEX with Finnish layout.

I'd say `<layout>us</layout>` -> `<layout>default</layout>` wouldn't have hurt, or even better, if it was configurable via GUI...

**Comment by lewtds** [comment]
@ztane that was actually what happened in 15362d1! Sadly this didn't make it to Ubuntu 16.04.
